# Configuration for prompt templates used in paper2slides
# This file defines all prompts used for LLM interactions

compiler:
  pdflatex_path: "pdflatex"

defaults:
  num_slides: 15
  max_items: 4
  audience: "machine learning professors, PhD students, and AI research scientists in AI/tech"
  figure_width: "0.75\\textwidth"
  figure_height: "0.75\\textheight"
  aspect_ratio: "169"
  font_size: "14pt"

stages:
  initial:
    system: "You are a professional assistant specialized in machine learning and deep learning, LaTeX, and Beamer."
    template: |
      Please read this paper and prepare {num_slides} Beamer slides. The intended audience includes {audience}. Ensure the slides are self-contained so that the content is understandable independently. Pay attention to the following guidelines:

      - Be very specific: Each slide should present detailed ideas. Use bullet points, but avoid being abstract and provide DETAILED information. For example:
        - Do not say "This paper provides insights into the new architecture." Instead, explain the specific insights and the architecture details.
        - Do not say "The proposed method demonstrates better accuracy than baselines." Instead, specify the tasks/benchmarks (e.g., dataset/benchmark names) where the proposed method excels, and quantify the improvement (e.g., 14% better accuracy).
      - Maximum number of `\\item` between `\\begin{{itemize}}` and `\\end{{itemize}}` is {max_items}. For example:

      ```latex
      \\begin{{itemize}}
      \\item 1st item
      \\item 2nd item
      \\item 3rd item
      \\item 4th item
      \\end{{itemize}}
      ```

      An exception is when you use equations. Then, it should be something like this.

      ```latex
      \\begin{{align}}
      Equation goes here...
      \\end{{align}}
      \\begin{{itemize}}
      \\item 1st item, explain notations/definitions carefully here.
      \\item 2nd item, explain the meaning of the equation here.
      \\end{{itemize}}
      ```

      - Logical Flow: Organize the slides in a logical sequence, typically following the structure of the paper:
        - First slide: should include the full title of the paper and the first author of the paper. Write only the last name and omit the first name. Write "\\author[]{{Author:  author name et al.}}". Use footnotesize font and centerize URLs. Make URLs clickable. No need to include today's date, but please include the date that the paper was released or uploaded to arxiv. This information is provided in the beginning of the paper. Note that the title, author, and date commands should be placed in the preamble and not in the first frame.
        - Next slide: executive summary of the paper.
        - Introduction slides: focus on the background and motivation of the paper. If necessary, highlight some issues of previous work. It shouldn't have too much overlap with the executive summary. Look for a figure that explains the overview of the proposed method. If such a figure exists, make a slide with that figure. This is very helpful for the reader.
        - Proposed method slides: such as the novel architecture, new loss function, new learning objective, new dataset, etc. this depends on the paper. Explain the core ideas and innovations that were introduced. Make sure to explain in detail since this is the MOST IMPORTANT PART. Explain WHY certain choices were made.
        - Result slides: such as the design of the experiments and the results. be super specific. whenever you say "significant improvement" or "superior results", explain quantitatively.
        - Concluding slides: you may use a slide for conclusion and future directions. Do NOT include a "Thank you" slide after the concluding slide.

      - Figures: As I have explained, look for a figure that explains the overview of the proposed method or a figure that demonstrates the superior performance of the proposed method. If there are such figures, include 1 or 2 figures in the beamer slides. An example of a figure in beamer:

      ```latex
      \\begin{{frame}}{{}}
        \\begin{{figure}}
          \\centering
          \\includegraphics[width=0.7\\textwidth,height=0.7\\textheight,keepaspectratio]{{example.png}}
          \\caption{{Only use up to 1 informative sentence here.}}
        \\end{{figure}}
      \\end{{frame}}
      ```
      Make sure to replace `example.png` with the actual figure file name with the correct path.
      Here is the list of image paths that you are allowed to use:
      {figure_paths}

      Do not use anything else. You often use images that do not exist, or choose the wrong extension. You shouldn't use the image files that are not used in the paper. Be careful!

      I prefer not to have frame title/bullet-point text in the slide if we are using the caption to explain the figure. Finally, don't forget `[width=0.7\\textwidth,height=0.7\\textheight,keepaspectratio]`!
      Furthermore, do NOT use the command `\\label`.

      - Equations and math: If there is an important equation, definitely include it! Examples are the learning objective or the equations that might be used in a novel neural network architecture. In such cases, also define the symbols/notations used. However, please enter a new line or make the font size smaller for long expressions because it won't fit in the slide.
      - Visual: you may use bold to emphasize some important keywords. use itemize instead of writing paragraphs. but make sure to write the full sentence.
      - Do not use the - character. It does not compile on my environment. Use - instead. Use abbreviations such as GANs, VAEs, SGD, LLM, and so on. use "w/" for "with" and "w/o" for "without".

      Begin your latex code with the following.
      ```latex
      \\documentclass[aspectratio={aspect_ratio},{font_size}]{{beamer}}
      \\input{{ADDITIONAL.tex}}
      \\usepackage{{mathtools,amssymb}}
      \\usepackage{{amsmath}}
      \\usepackage{{bm}}
      \\usetheme{{Berlin}}
      \\usecolortheme{{dolphin}}
      \\usefonttheme{{professionalfonts}}
      \\setbeamertemplate{{footline}}{{}}
      \\institute{{\\normalsize created by paper2slides}}
      \\setbeamersize{{text margin left=0.1cm, text margin right=0.3cm}}
      \\setbeamertemplate{{headline}}{{}}
      \\setbeamertemplate{{section in head/foot}}{{}}
      \\setbeamertemplate{{subsection in head/foot}}{{}}
      \\setbeamertemplate{{navigation symbols}}{{}}
      \\setbeamertemplate{{footline}}{{
        \\leavevmode%
        \\hbox{{%
        \\begin{{beamercolorbox}}[wd=.5\\paperwidth,ht=2.25ex,dp=1ex,right]{{title in head/foot}}%
          \\usebeamerfont{{title in head/foot}}\\insertshorttitle\\hspace*{{2ex}}
        \\end{{beamercolorbox}}%
        \\begin{{beamercolorbox}}[wd=.5\\paperwidth,ht=2.25ex,dp=1ex,left]{{date in head/foot}}%
          \\usebeamerfont{{date in head/foot}}\\hspace*{{2ex}}
        \\end{{beamercolorbox}}}}%
        \\vskip0pt%
      }}
      ```

      Note that `ADDITIONAL.tex` includes all packages and new commands defined in the original paper and `ADDITIONAL.tex` exists in the current directory. Make sure to include this in the beamer code.

      Make sure to provide the final perfect polished version because I will use it directly without editing further.

      Paper content:
      {latex_source}

      Now provide the latex source code: start with ```latex, provide latex code, and then end with ```. Provide the full latex source code at once.

  update:
    system: "You are a professional assistant specialized in machine learning and deep learning, LaTeX, and Beamer."
    template: |
      Based on the paper above, we have the slide version written in beamer. I want you to read the paper and beamer code, and provide a revised version of it. Pay attention to the following:
      - If you find any bugs or errors, fix it. Pay attention to syntax issues.
      - Does the paper include a figure that explains the main ideas of the proposed method? If the paper has one, it would be a good idea to also have it in the slides.
      - If the beamer code uses any figures, is the path correct? Make sure the path, file name, and file extension are equivalent to the information in the paper. For example, if the paper is using `figures/image.png`, we should also use that in our beamer code rather than `image.png`. Similarly, if the paper is using `image.png`, we should also use `image.png` rather than `figures/image.png`. For your information, the original paper uses {figure_paths} for figures. Be extra careful with the file names since you tend to make mistakes.
      - The beamer slides are 16:9 aspect ratio. If you think an equation is too long, we can add new lines to the equation. If it is a very complicated equation, consider removing the equation and try to explain it with natural language. If you think the table might not fit, consider making the font size smaller for the table.
      - Make sure escape characters are used with a backslash. For example, if you are using ampersand as a regular character, you need to escape it unless you are using it with a special meaning (e.g., using it in alignment in tables and arrays.)
      - If commands such as `\\cite` or `\\bibliography` are used for citation, remove them. We do not have a bib file.
      - If there is a figure in a frame, DON'T use any text other than the caption of the figure. So this means we shouldn't have `itemize` or even a title in a frame with a figure. Having a one-sentence caption is encouraged. Furthermore, use only up to one figure per a frame. An example of using a figure:
      ```latex
      \\begin{{frame}}{{}}
        \\begin{{figure}}
          \\centering
          \\includegraphics[width={figure_width},height={figure_height},keepaspectratio]{{FIGURE_PATH}}
          \\caption{{Performance trade-off vs. cost.}}
        \\end{{figure}}
      \\end{{frame}}
      ```

      Always use this specific setup: `[width={figure_width},height={figure_height},keepaspectratio]` for `includegraphics`.

      Paper content:
      {latex_source}

      Current slides:
      {beamer_code}

      Now provide the latex source code: start with ```latex, provide latex code, and then end with ```. Provide the full latex source code at once.

  revise:
    system: "You are a professional assistant specialized in machine learning and deep learning, LaTeX, and Beamer."
    template: |
      We are trying to create presentation slides of a research paper, and we have prepared a beamer presentation shown above.
      We also provide you with the chktex results showing warnings and errors of the beamer code, if any.
      Note that ADDITIONAL.tex is a file that includes many new commands and other definitions.
      You do not have access to ADDITIONAL.tex, so ignore the warnings/errors included in ADDITIONAL.tex.
      I want you to read the beamer code and chktex results, and provide a revised version of it.

      Pay attention to the following:
      - If you find any bugs or errors, fix it. Pay attention to syntax issues. The ChkTeX results should be helpful, if provided.
      - You sometimes get confused with HTML syntax (with delimiters). DON'T DO THIS!! LaTeX please!!
      - If the beamer code uses any figures, is the path correct? Make sure the path, file name, and file extension are equivalent to the information in the paper. For example, if the paper is using `figures/image.png`, we should also use that in our beamer code rather than `image.png`. Similarly, if the paper is using `image.png`, we should also use `image.png` rather than `figures/image.png`. For your information, the original paper uses {figure_paths} for figures. Be extra careful with the file names since you tend to make mistakes.
      - The beamer slides are 16:9 aspect ratio. If you think an equation is too long, we can add new lines to the equation. If it is a very complicated equation, consider removing the equation and try to explain it with natural language. If you still decide to use equations, make sure you explain the notations. If you think the table might not fit, consider making the font size smaller for the table.
      - Make sure escape characters are used with a backslash. For example, if you are using ampersand as a regular character, you need to escape it unless you are using it with a special meaning (e.g., using it in alignment in tables and arrays.) Don't forget to use escape-percentage character with a backslash! Otherwise, it will become a comment in LaTeX. For example, `73%` will comment out everything after the number and should be `73\\%` instead.
      - If commands such as `\\cite` or `\\bibliography` are used for citation, remove them. We do not have a bib file.
      - If there is a figure in a frame, DON'T use any text other than the caption of the figure. So this means we shouldn't have `itemize` or even a title in a frame with a figure. Furthermore, use only up to one figure per a frame. A caption is important though, and should explain the figure in 1 sentence. An example of using a figure:
      ```latex
      \\begin{{frame}}{{}}
        \\begin{{figure}}
          \\centering
          \\includegraphics[width={figure_width},height={figure_height},keepaspectratio]{{FIGURE_PATH}}
          \\caption{{Performance trade-off vs. cost.}}
        \\end{{figure}}
      \\end{{frame}}
      ```

      Always use this specific setup: `[width={figure_width},height={figure_height},keepaspectratio]` for `includegraphics`.

      Paper content:
      {latex_source}

      Current slides:
      {beamer_code}

      ChkTeX results:
      {linter_log}

      Now provide the latex source code: start with ```latex, provide latex code, and then end with ```. Provide the full latex source code at once.

  interactive_edit:
    system: "You are a professional assistant specialized in LaTeX and Beamer. Your task is to revise a Beamer presentation based on user instructions."
    template: |
      You are given a Beamer presentation and a set of instructions from the user on how to edit it. Please apply the edits and provide the complete, revised LaTeX source code for the presentation.

      User Instructions:
      "{user_instructions}"

      Original Paper Source (for context):
      {latex_source}

      Current Beamer Code:
      {beamer_code}

      Now, provide the full, updated LaTeX source code for the Beamer presentation. Start with ```latex, provide the code, and end with ```.
